#!/bin/bash
# Run the single-time RTMA-OK encoder diagnostic.
#
# This script does NOT run inference. Run
#   training/new-tl-infer-encoder-rtma_ok_sfc.sh
# first, so that RUN_DIR contains:
#   unnorm_preds_0.npy
#   unnorm_targets_0.npy
#
# The Python diagnostic then reads, for ANALYSIS_TIME:
#   1. the saved Aardvark prediction and URMA truth from RUN_DIR;
#   2. the same day's normalized 00 UTC background from DATA_ROOT;
#   3. the valid observations for the selected variable and hour from DATA_ROOT;
#   4. the grid, monthly filename templates, and normalization paths from GRID_CONFIG.
#
# It writes a 3-by-3 diagnostic PNG and a CSV table containing full-domain,
# near-observation, and far-from-observation RMSE/bias/skill metrics.
#
# This can be run directly on a login/analysis node if local policy permits:
#   bash scripts/run_diagnose_encoder_analysis.sh
#
# It can also be submitted as a small Slurm job:
#   sbatch scripts/run_diagnose_encoder_analysis.sh

#SBATCH -A fv3-cam
#SBATCH -J av-ok-diagnostic
#SBATCH -p u1-h100
#SBATCH -q gpuwf
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --open-mode=truncate
#SBATCH -t 00:20:00
#SBATCH -o diagnose-aardvark-ok.%j.out
#SBATCH -e diagnose-aardvark-ok.%j.err

set -euo pipefail

# -----------------------------------------------------------------------------
# USER SETTINGS: normally only edit this section.
# -----------------------------------------------------------------------------

# UTC analysis time. It must be aligned with TIME_FREQ. For 1H, minutes must be 00.
ANALYSIS_TIME="2022-01-15T06:00"

# Output channel to diagnose:
#   0 = t2m, matched with tas observation locations
#   1 = q2m, matched with sh observation locations
#   2 = sp,  matched with psl observation locations
#   3 = u10, matched with u observation locations
#   4 = v10, matched with v observation locations
CHANNEL=0

# A grid point is classified as "near observations" when a valid observation of
# the selected variable is within this great-circle distance. All remaining grid
# points are classified as "far from observations."
OBS_RADIUS_KM=25

# Rank suffix of the inference arrays. A one-GPU inference normally writes rank 0.
RANK=0

# Current tool supports exactly one saved inference sample, whose index is zero.
SAMPLE_INDEX=0

# Cadence and target mode used by the inference run.
TIME_FREQ="1H"
ERA5_MODE="rtma_ok_sfc"

# Root containing urma/, hadisd_processed/, norm_factors/, and model_data_dir/.
DATA_ROOT="/scratch3/NCEPDEV/fv3-cam/Ting.Lei/dr-rtma-data/dr-av-rtma_ok_data"

# Base directory under which the inference script creates OK-infer-<timestamp>/.
INFERENCE_ROOT="/scratch3/NCEPDEV/fv3-cam/Ting.Lei/aardvark-data/dr-rtma"

# -----------------------------------------------------------------------------
# END USER SETTINGS
# -----------------------------------------------------------------------------

# Activate the same environment used for Aardvark training and inference.
source /scratch3/NCEPDEV/fv3-cam/Ting.Lei/dr-miniconda3/bin/activate aardvark-env

# On Ursa, a previously loaded spack-stack module may put an incompatible Python
# installation on PYTHONPATH. Clearing it ensures packages come from aardvark-env.
unset PYTHONPATH

# Resolve the repository from this script's location. This makes the wrapper
# independent of the directory from which bash/sbatch was invoked.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
GRID_CONFIG="${REPO_ROOT}/aardvark/grid_config_ok.yaml"
PYTHON_TOOL="${REPO_ROOT}/scripts/diagnose_encoder_analysis.py"

# Match the token generated by new-tl-infer-encoder-rtma_ok_sfc.sh:
#   2022-01-15T06:00 -> 20220115T0600
TIME_TOKEN=${ANALYSIS_TIME//[-:]/}
RUN_DIR="${INFERENCE_ROOT}/OK-infer-${TIME_TOKEN}"

# Fail before Python starts if the main inputs or configuration are missing.
[[ -d "${DATA_ROOT}" ]] || {
  echo "ERROR: RTMA data root not found: ${DATA_ROOT}" >&2
  exit 1
}
[[ -d "${RUN_DIR}" ]] || {
  echo "ERROR: inference output directory not found: ${RUN_DIR}" >&2
  echo "Run training/new-tl-infer-encoder-rtma_ok_sfc.sh for ${ANALYSIS_TIME} first." >&2
  exit 1
}
[[ -f "${RUN_DIR}/unnorm_preds_${RANK}.npy" ]] || {
  echo "ERROR: prediction file not found: ${RUN_DIR}/unnorm_preds_${RANK}.npy" >&2
  exit 1
}
[[ -f "${RUN_DIR}/unnorm_targets_${RANK}.npy" ]] || {
  echo "ERROR: target file not found: ${RUN_DIR}/unnorm_targets_${RANK}.npy" >&2
  exit 1
}
[[ -f "${GRID_CONFIG}" ]] || {
  echo "ERROR: grid configuration not found: ${GRID_CONFIG}" >&2
  exit 1
}
[[ -f "${PYTHON_TOOL}" ]] || {
  echo "ERROR: diagnostic Python tool not found: ${PYTHON_TOOL}" >&2
  exit 1
}

echo "RTMA-OK encoder diagnostic"
echo "  analysis time:       ${ANALYSIS_TIME} UTC"
echo "  inference directory: ${RUN_DIR}"
echo "  data root:           ${DATA_ROOT}"
echo "  channel:             ${CHANNEL}"
echo "  observation radius:  ${OBS_RADIUS_KM} km"
echo "  grid configuration:  ${GRID_CONFIG}"

# The Python tool automatically names its PNG and CSV under RUN_DIR. It also:
#   - confirms the saved truth matches the raw monthly target at ANALYSIS_TIME;
#   - denormalizes the background with the target mean/std;
#   - verifies against background_raw_* when that optional file exists;
#   - uses finite observations of the selected variable to define near/far masks.
python "${PYTHON_TOOL}" \
  --run_dir "${RUN_DIR}" \
  --analysis_time "${ANALYSIS_TIME}" \
  --data_root "${DATA_ROOT}" \
  --grid_config "${GRID_CONFIG}" \
  --era5_mode "${ERA5_MODE}" \
  --time_freq "${TIME_FREQ}" \
  --rank "${RANK}" \
  --sample_index "${SAMPLE_INDEX}" \
  --channel "${CHANNEL}" \
  --obs_radius_km "${OBS_RADIUS_KM}"

echo "Diagnostic completed. New PNG/CSV products in: ${RUN_DIR}"
ls -lh "${RUN_DIR}"/diagnostic_"${TIME_TOKEN}"_*.png \
       "${RUN_DIR}"/diagnostic_"${TIME_TOKEN}"_*.csv
